// Initialize the app
export const INIT_APP = 'INIT_APP';
export const LOAD_DATA = 'LOAD_DATA';
// Students
export const ADD_STUDENT = 'ADD_STUDENT';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';
export const REMOVE_STUDENT = 'REMOVE_STUDENT';
export const FETCH_STUDENTS = 'FETCH_STUDENTS';
export const LOAD_STUDENTS_FROM_GOOGLE_SHEETS = 'LOAD_STUDENTS_FROM_GOOGLE_SHEETS';

// Tutor
export const TUTOR_NAME = 'TUTOR_NAME';
export const TUTOR_ROSTER_NAME = 'TUTOR_ROSTER_NAME';
export const TUTOR_GOOGLE_SHEET_URL = 'TUTOR_GOOGLE_SHEET_URL';

// Google Calendar
export const ADD_EVENT = 'ADD_EVENT';
export const LOAD_EVENTS = 'LOAD_EVENTS';

// Templates
export const ADD_TEMPLATE = 'ADD_TEMPLATE';
export const EDIT_TEMPLATE = 'EDIT_TEMPLATE';
export const DELETE_TEMPLATE = 'DELETE_TEMPLATE';
export const UPDATE_CURRENT_TEMPLATE = 'UPDATE_CURRENT_TEMPLATE';
export const UPDATE_SELECTED_TEMPLATE = 'UPDATE_SELECTED_TEMPLATE';

// Gmail
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const GET_GMAIL_MESSAGE = 'GET_GMAIL_MESSAGE';
export const GET_GMAIL_MESSAGE_PENDING = 'GET_GMAIL_MESSAGE_PENDING';
export const GET_GMAIL_MESSAGE_REJECTED = 'GET_GMAIL_MESSAGE_REJECTED';
export const GET_GMAIL_MESSAGE_FULFILLED = 'GET_GMAIL_MESSAGE_FULFILLED';

// Tutor Gmail Profile
export const GET_GMAIL_PROFILE = 'GET_GMAIL_PROFILE';
export const GET_GMAIL_PROFILE_FULFILLED = 'GET_GMAIL_PROFILE_FULFILLED';
export const GET_GMAIL_PROFILE_REJECTED = 'GET_GMAIL_PROFILE_REJECTED';
export const GET_GMAIL_PROFILE_PENDING = 'GET_GMAIL_PROFILE_PENDING';


// Email
export const SEND_EMAIL_TO_GOOGLE=  'SEND_EMAIL_TO_GOOGLE';
export const SEND_EMAIL_TO_GOOGLE_REJECTED=  'SEND_EMAIL_TO_GOOGLE_REJECTED';
export const SEND_EMAIL_TO_GOOGLE_PENDING=  'SEND_EMAIL_TO_GOOGLE_PENDING';
export const SEND_EMAIL_TO_GOOGLE_FULFILLED=  'SEND_EMAIL_TO_GOOGLE_FULFILLED';

export const REQUEST_TO_SEND_EMAIL = 'REQUEST_TO_SEND_EMAIL';

export const UPDATE_RECEIVER_SUBJECT = 'UPDATE_RECEIVER_SUBJECT';
export const UPDATE_RECEIVER_EMAIL = 'UPDATE_RECEIVER_EMAIL';
export const UPDATE_RECEIVER_MSG = 'UPDATE_RECEIVER_MSG';

export const UPDATE_RECEIVER_DETAILS = 'UPDATE_RECEIVER_DETAILS';

// Routing
export const CURRENT_ROUTE = 'CURRENT_ROUTE';

// List of integrations
export const GMAIL_INTEGRATION_FULFILLED = 'GMAIL_INTEGRATION_FULFILLED';
export const GMAIL_INTEGRATION_REJECTED = 'GMAIL_INTEGRATION_REJECTED';


// Notifications
export const SEND_NOTIFICATION = 'SEND_NOTIFICATION';
export const RESET_NOTIFICATION = 'RESET_NOTIFICATION';