// Students
export const ADD_STUDENT = 'ADD_STUDENT';
export const REMOVE_STUDENT = 'REMOVE_STUDENT';
export const FETCH_STUDENTS = 'FETCH_STUDENTS';

// Tutor
export const TUTOR_NAME = 'TUTOR_NAME';
export const TUTOR_ROSTER_NAME = 'TUTOR_ROSTER_NAME';
export const TUTOR_GOOGLE_SHEET_URL = 'TUTOR_GOOGLE_SHEET_URL';

// Google Calendar
export const ADD_EVENT = 'ADD_EVENT';
export const LOAD_EVENTS = 'LOAD_EVENTS';

// Templates
export const ADD_TEMPLATE = 'ADD_TEMPLATE';

// Messages
export const LOAD_MESSAGES = 'LOAD_MESSAGES';
export const LOAD_MESSAGES_PENDING = 'LOAD_MESSAGES_PENDING';
export const LOAD_MESSAGES_FULFILLED = 'LOAD_MESSAGES_FULFILLED';
export const LOAD_MESSAGES_REJECTED = 'LOAD_MESSAGES_REJECTED';

export const ADD_MESSAGE = 'ADD_MESSAGE';
export const GET_GMAIL_MESSAGE = 'GET_GMAIL_MESSAGE';
export const GET_GMAIL_MESSAGE_PENDING = 'GET_GMAIL_MESSAGE_PENDING';
export const GET_GMAIL_MESSAGE_REJECTED = 'GET_GMAIL_MESSAGE_REJECTED';
export const GET_GMAIL_MESSAGE_FULFILLED = 'GET_GMAIL_MESSAGE_FULFILLED';

export const SEND_EMAIL_TO_GOOGLE=  'SEND_EMAIL_TO_GOOGLE';
export const SEND_EMAIL_TO_GOOGLE_REJECTED=  'SEND_EMAIL_TO_GOOGLE_REJECTED';
export const SEND_EMAIL_TO_GOOGLE_PENDING=  'SEND_EMAIL_TO_GOOGLE_PENDING';
export const SEND_EMAIL_TO_GOOGLE_FULFILLED=  'SEND_EMAIL_TO_GOOGLE_FULFILLED';